### ISSUE TITLE
Show greeting only for first start

### ISSUE THREAD

**Issue by rlopzc** [creekpld/theme-pld#2]
Using iTerm

![image](https://user-images.githubusercontent.com/6199588/49244868-710c9100-f3d6-11e8-98be-e023c0c0b351.png)

Each session displays the greeting message. It would be awesome to just show it on first init

**Comment by creekpld** [comment]
a good idea, done!
you can now call ***fish_greeting -v*** if you still want the greeting in subsequent login sessions.
